import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import MintForm from "../components/MintForm";
import MintGallery from "../components/MintGallery";
import styles from "../styles/Home.module.css";
import Navbar from "./../components/Navbar";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <Hero />
        <MintForm />
        <MintGallery />
      </main>
    </div>
  );
};

export default Home;
